[[tasks]]
name = "setup"
command = "bun i"

[[tasks]]
name = "dev"
command = "bun --watch run.ts"

[[tasks]]
name = "leetcode"
command = "bun --watch leetcode/$1-*.ts"

[[tasks]]
name = "pattern"
command = "bun --watch patterns/$1.ts"

[[tasks]]
name = "cli"
command = "bun cli/main.ts $@"
